GetHTML.py, 33, (<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='newzbots.me', port=80): Max retries exceeded with url: /?23Y0HC%0A%0A (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3571e8f7b8>: Failed to establish a new connection: [Errno 110] Connection timed out',))",),), <traceback object at 0x7f3571ead288>)
