GetHTML.py, 33, (<class 'requests.exceptions.ConnectionError'>, ConnectionError(MaxRetryError("HTTPSConnectionPool(host='home.twibble.io%0a', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3571be5c18>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),), <traceback object at 0x7f3571ea66c8>)
